/* DO NOT EDIT, file generated by nestjs-i18n */

/* eslint-disable */
/* prettier-ignore */
import { Path } from "nestjs-i18n";
/* prettier-ignore */
export type I18nTranslations = {
    "general": {
        "welcome": string;
        "error": {
            "notFound": string;
            "unauthorized": string;
            "forbidden": string;
            "internalServerError": string;
            "badRequest": string;
            "somethingWentWrong": string;
            "notImplemented": string;
            "validation": string;
            "invalidCredentials": string;
            "invalidToken": string;
            "tokenRequired": string;
            "tokenExpired": string;
            "tokenAlive": string;
            "sessionNotFound": string;
        };
        "success": {
            "created": string;
            "updated": string;
            "deleted": string;
            "retrieved": string;
            "operation": string;
        };
    };
};
/* prettier-ignore */
export type I18nPath = Path<I18nTranslations>;
